stages:
    - compile

image:
    name: maven:3.8.5-openjdk-8

before_script:
    - apt install -y ansible
    - ansible --version

build hello-world:
    stage: compile
    script:
        - mvn clean install package
    artifacts:
        paths:
            - /builds

