stages:
    - compile
    - docker_build

image:
    name: maven:3.8.5-openjdk-8

before_script:
    - apt update
    - apt install -y ansible
    - ansible --version

build hello-world:
    stage: compile
    script:
        - mvn clean install package
    artifacts:
        paths:
            - /builds

build docker images:
    stage: docker_build
    image: docker:stable
    service: docker:stable-dind
    script:
        - echo "Docker build"
        - cp /builds/hmeftah/hello-world/webapp/target/webapp/webapp.war . 
        - docker build -t webapp-afip .

