stages:
    - compile
    - docker_build

build hello-world:
    stage: compile
    image: maven:3.8.5-openjdk-8
    script:
        - mvn clean install package
    artifacts:
        paths:
            - /builds

build docker images:
    stage: docker_build
    image: docker:stable
    services: 
        - docker:stable-dind
    script:
        - echo "Docker build"
        - cp /builds/hmeftah/hello-world/webapp/target/webapp.war . 
        - docker version


      

